In [1]:
import pandas as pd
import numpy as np
import scipy
from scipy import stats

In [2]:
stats.t.cdf(2.23, df=10)

0.9750787646106596

In [3]:
stats.t.cdf(2.23, df=79)

0.9857070911974259

In [4]:
1 - stats.t.cdf(2.23, df=79)

0.014292908802574056

# Call Center example

In [5]:
(4-4.6)/(3/np.sqrt(50))

-1.4142135623730943

In [6]:
2* stats.t.cdf(-1.41, df= 49)

0.1648559451804547

In [7]:
(4-3.7)/(3/np.sqrt(50))

0.7071067811865471

In [8]:
2* stats.t.cdf(0.70, df= 49)

1.5127624104501614

In [9]:
(4-4.2)/(3/np.sqrt(50))

-0.4714045207910321

In [10]:
2* stats.t.cdf(-0.47, df= 49)

0.640440149558531

In [11]:
(4-4.0)/(3/np.sqrt(50))

0.0

In [12]:
2* stats.t.cdf(-0.0, df= 49)

1.0

# One tail test

In [13]:
import pandas as pd
import numpy as np
import scipy
from scipy import stats

In [14]:
data=pd.Series([0.593,0.142,0.329,0.691,0.231,0.793,0.519,0.392,0.418])

In [15]:
data

0    0.593
1    0.142
2    0.329
3    0.691
4    0.231
5    0.793
6    0.519
7    0.392
8    0.418
dtype: float64

In [16]:
#This gives two tail test p value so divide by 2 to get final p-value
p= scipy.stats.ttest_1samp(data,0.3)[1]

In [17]:
p

0.05853032968489765

In [18]:
p/2

0.029265164842448826

# Two tail test

In [19]:
Control = pd.Series([91,87,99,77,88,91])
Treat = pd.Series([101,110,103,93,99,104])

In [20]:
stats.ttest_ind(Control, Treat)

Ttest_indResult(statistic=-3.445612673536487, pvalue=0.006272124350809803)

In [21]:
import numpy as np

In [22]:
#data
n1 = 247
p1 = .37

n2 = 308
p2 = .39

In [23]:
population1 = np.random.binomial(1, p1, n1)
population2 = np.random.binomial(1, p2, n2)

In [24]:
population1.mean()

0.2834008097165992

In [25]:
population2.mean()

0.39935064935064934

In [26]:
population2

array([0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1,

In [27]:
population1

array([0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 1, 1])

In [28]:
import statsmodels.api as sm
sm.stats.ttest_ind(population1, population2)

(-2.8663288033362355, 0.0043107574038610845, 553.0)

# Anova

In [29]:
#Load Libraries
from sklearn import datasets


In [30]:
# Load digits dataset
iris = datasets.load_iris()


In [31]:
df = pd.DataFrame(iris.data)

In [32]:
df

0    1    2    3
0    5.1  3.5  1.4  0.2
1    4.9  3.0  1.4  0.2
2    4.7  3.2  1.3  0.2
3    4.6  3.1  1.5  0.2
4    5.0  3.6  1.4  0.2
..   ...  ...  ...  ...
145  6.7  3.0  5.2  2.3
146  6.3  2.5  5.0  1.9
147  6.5  3.0  5.2  2.0
148  6.2  3.4  5.4  2.3
149  5.9  3.0  5.1  1.8

[150 rows x 4 columns]

In [33]:
import scipy.stats as stats
stats.f_oneway(df.iloc[:,0], df.iloc[:,1],df.iloc[:,2])

F_onewayResult(statistic=236.75163298404746, pvalue=7.657188374182084e-71)

# In the first cell, we are going to import chi2_contingency , pandas and numpy libraries.

In [34]:
import pandas as pd
import numpy as np
import scipy
from scipy import stats
from scipy.stats import chi2_contingency

# Pandas index and columns are used to name rows and columns. In order to print what's in our tshirts variable, we just write tshirts at the end and enter SHIFT + RETURN.

In [35]:
data = pd.DataFrame([
    [14,4,18],[0,10,10],[14,14,28]],
                   index = ["Athlete","Non-athlete","Total"],
                   columns = ["Non-smoker", "Smoker","Total"])
data

Non-smoker  Smoker  Total
Athlete              14       4     18
Non-athlete           0      10     10
Total                14      14     28

In [36]:
#You can find what the labels in the columns are by using columns.
data.columns

Index(['Non-smoker', 'Smoker', 'Total'], dtype='object')

In [37]:
data.index

Index(['Athlete', 'Non-athlete', 'Total'], dtype='object')

# chi2_contingency

In [38]:
#SciPy’s chi2_contingency() returns four values, 𝜒2 value, p-value, degree of freedom and expected values.
chi2_contingency(data)

(15.555555555555555,
 0.0036773808613802627,
 4,
 array([[ 9.,  9., 18.],
        [ 5.,  5., 10.],
        [14., 14., 28.]]))

# Expected values

In [39]:
#You can find the expected values at the forth in the returned value. It is in an array form. Let’s print the expected values in a friendly way. We again use the Pandas dataframe. We are going to add index and column values and round the values to the two decimal places round(2).
df=chi2_contingency(data)[3]
pd.DataFrame(
    data=df[:,:], 
    index=["Athlete","Non-athlete","Total"],
    columns=["Non-smoker", "Smoker","Total"]
).round(2)

Non-smoker  Smoker  Total
Athlete             9.0     9.0   18.0
Non-athlete         5.0     5.0   10.0
Total              14.0    14.0   28.0

In [40]:
#This is what chi2_contingency is doing behind the scene. Since Python is 0 based index, in order to print the 𝜒2 we need to use [0] which is the first value.
chisquare=chi2_contingency(data)[0]
chisquare

15.555555555555555

# p-value

In [41]:
# You can find the p-value at the second in the returned value. p-value measures the probability of seeing the effect when the null hypothesis is true. So, when the p-value is low enough, we reject the null hypothesis and conclude the observed effect holds.
pvalue=chi2_contingency(data)[1]
pvalue

0.0036773808613802627

# Degree of freedom

In [42]:
#In the returned value from the chi2_contingency, the third one is the degree of freedom. We use [2] which is the third one. The following will output 3.
dof=chi2_contingency(data)[2]
dof

4

# Critical values

In [43]:
#The level of significance and degree of freedom can be used to find the critical value. As I mentioned before you can find the degree of freedom from the array. In order to find critical values, you need to import chi2 from scipy.state and define probability from the level of significance, 1%, 5% 10%, etc.
from scipy.stats import chi2
significance = 0.01
p = 1 - significance
dof = chi2_contingency(data)[2]
critical_value = chi2.ppf(p, dof)
critical_value

13.276704135987622

In [44]:
p = chi2.cdf(critical_value, dof)
p

0.99